### ISSUE TITLE
Collisions Check: Can't access a member of class CraftPlayer with modifiers "public"

### ISSUE THREAD

**Issue by TiTo-418** [pgmann/SpectatorPlus#64] opened 2016-05-02 10:55 UTC
```
[07:50:35 ERROR]: [SpectatorPlus] Reflection exception caught while trying to check collisions status for TiTo_418
java.lang.IllegalAccessException: Class com.pgcraft.spectatorplus.tools.reflection.Reflection can not access a member of class org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer$1 with modifiers "public"
        at sun.reflect.Reflection.ensureMemberAccess(Unknown Source) ~[?:1.8.0_74]
        at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(Unknown Source) ~[?:1.8.0_74]
        at java.lang.reflect.AccessibleObject.checkAccess(Unknown Source) ~[?:1.8.0_74]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_74]
        at com.pgcraft.spectatorplus.tools.reflection.Reflection.call(Reflection.java:316) ~[SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at com.pgcraft.spectatorplus.tools.reflection.Reflection.call(Reflection.java:286) ~[SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at com.pgcraft.spectatorplus.utils.Collisions.collidesWithEntities(Collisions.java:68) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at com.pgcraft.spectatorplus.spectators.Spectator.enableSpectatorMode(Spectator.java:186) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at com.pgcraft.spectatorplus.spectators.Spectator.setSpectating(Spectator.java:156) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at com.pgcraft.spectatorplus.spectators.Spectator.setSpectating(Spectator.java:135) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at com.pgcraft.spectatorplus.spectators.Spectator.setSpectating(Spectator.java:112) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at com.pgcraft.spectatorplus.spectators.Spectator.setSpectating(Spectator.java:101) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at com.pgcraft.spectatorplus.SpectateAPI.setSpectating(SpectateAPI.java:95) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at eu.carrade.amaury.UHCReloaded.spectators.SPlusSpectatorsManager.setSpectating(SPlusSpectatorsManager.java:54) [UHCReloaded-1.3-SNAPSHOT%20(2).jar:?]
        at eu.carrade.amaury.UHCReloaded.listeners.GameListener$5.run(GameListener.java:312) [UHCReloaded-1.3-SNAPSHOT%20(2).jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
```

Lastest github version

**Comment by pgmann** [comment] 2016-05-02 14:17
UHC Reloaded called `setSpectating()` event. I don't usually test the plugin with UHC Reloaded installed. @AmauryCarrade, any input?

**Comment by AmauryCarrade** [comment] 2016-05-02 19:45
I'll check that when possible.

**Comment by pgmann** [comment] 2016-05-03 18:27
Note, this is a duplicate of #60 (just noticed). That rules out UHPlugin being at fault since I reproduced this without that plugin installed.

**Comment by TiTo-418** [comment] 2016-05-03 21:46
Let's keep track on #60

**Closed** 2016-05-03 21:46 UTC
Labels: Bug, Duplicate
