### ISSUE TITLE
Scoreboards problem (accessed when unregistered)

### ISSUE THREAD

**Issue by MrBeefchop** [pgmann/SpectatorPlus#55] opened 2015-10-12 22:52 UTC
When I make /spec on I got an error and i am anywhere! I had make the Setup!

```
[00:50:21 WARN]: java.lang.reflect.InvocationTargetException
[00:50:21 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:50:21 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:50:21 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorI
mpl.java:43)
[00:50:21 WARN]: at java.lang.reflect.Method.invoke(Method.java:497)
[00:50:21 WARN]: at com.pgcraft.spectatorplus.SpectateCommand.onCommand(SpectateCommand.java:82)
[00:50:21 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:50:21 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[00:50:21 WARN]: at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.ja
va:645)
[00:50:21 WARN]: at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[00:50:21 WARN]: at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[00:50:21 WARN]: at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[00:50:21 WARN]: at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[00:50:21 WARN]: at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[00:50:21 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[00:50:21 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[00:50:21 WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683)
[00:50:21 WARN]: at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[00:50:21 WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[00:50:21 WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[00:50:21 WARN]: at java.lang.Thread.run(Thread.java:745)
[00:50:21 WARN]: Caused by: java.lang.IllegalStateException: Unregistered scoreboard component
[00:50:21 WARN]: at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftScoreboardComponent.checkState(CraftScoreboardComponent.java:13)
[00:50:21 WARN]: at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftTeam.addEntry(CraftTeam.java:148)
[00:50:21 WARN]: at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftTeam.addPlayer(CraftTeam.java:143)
[00:50:21 WARN]: at com.pgcraft.spectatorplus.SpectatorPlus.enableSpectate(SpectatorPlus.java:756)
[00:50:21 WARN]: at com.pgcraft.spectatorplus.SpectatorPlus.enableSpectate(SpectatorPlus.java:696)
[00:50:21 WARN]: at com.pgcraft.spectatorplus.SpectatorPlus.enableSpectate(SpectatorPlus.java:683)
[00:50:21 WARN]: at com.pgcraft.spectatorplus.SpectateCommand.doOn(SpectateCommand.java:262)
[00:50:21 WARN]: ... 20 more
>
```

And it says: Stay in the Arena!
By /spec off the same...

When I make /spec reload an error:

```
[00:48:31 WARN]: java.lang.reflect.InvocationTargetException
[00:48:31 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:48:31 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:48:31 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:48:31 WARN]: at java.lang.reflect.Method.invoke(Method.java:497)
[00:48:31 WARN]: at com.pgcraft.spectatorplus.SpectateCommand.onCommand(SpectateCommand.java:82)
[00:48:31 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:48:31 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[00:48:31 WARN]: at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[00:48:31 WARN]: at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[00:48:31 WARN]: at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[00:48:31 WARN]: at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[00:48:31 WARN]: at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[00:48:31 WARN]: at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[00:48:31 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[00:48:31 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[00:48:31 WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683)
[00:48:31 WARN]: at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[00:48:31 WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[00:48:31 WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[00:48:31 WARN]: at java.lang.Thread.run(Thread.java:745)
[00:48:31 WARN]: Caused by: java.lang.IllegalStateException: Unregistered scoreboard component
[00:48:31 WARN]: at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftScoreboardComponent.checkState(CraftScoreboardComponent.java:13)
[00:48:31 WARN]: at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftTeam.getPlayers(CraftTeam.java:112)
[00:48:31 WARN]: at com.pgcraft.spectatorplus.SpectatorPlus.reloadConfig(SpectatorPlus.java:1130)
[00:48:31 WARN]: at com.pgcraft.spectatorplus.SpectateCommand.doReload(SpectateCommand.java:320)
[00:48:31 WARN]: ... 20 more
[00:48:33 INFO]:
```

The other Commands works fine!

Spigot: 1.8 | 13716d9-0899683 (SNAPSHOT)

Client Version: 1.8.7 + Optifine!

**Comment by pgmann** [comment] 2015-10-13 08:18
Do you have any plugins that modify the scoreboard? The problem is caused
by: java.lang.IllegalStateException: Unregistered scoreboard component.
This leads me to believe it's being modified in some way...

**Comment by AmauryCarrade** [comment] 2015-12-29 12:06
Fixed in the `rewrite` branch.

**Closed by AmauryCarrade** 2015-12-29 12:06 UTC
Labels: Bug
